config/routes.rb
Rails.application.routes.draw do
  
  get '/contact', to: 'static_pages#contact'
  get 'users/index'
  get 'users/show'
  get '/post', to: 'microposts#post'
  post "likes/:micropost_id/create" => "likes#create"
  post "likes/:micropost_id/destroy" => "likes#destroy"
  root 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users, only: [:index, :show, :edit]
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts
  resources :relationships, only:[:create, :destroy]
  resources :searches
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, {presence: true}
  validates :post_id, {presence: true}
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :picture, {presence: true}
  default_scope -> {order(created_at: :desc)}
  mount_uploader :picture, PictureUploader
  
  def self.search(search)
    if search
      Micropost.where(['content LIKE ?', "%#{search}%"])
    else
      Micropost.all
    end
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/search.rb
class Search < ApplicationRecord
  def self.search(search)
    if search 
      Search.where(['name LIKE ?', "%#{search}%"])
    else
      Search.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                  foreign_key: "follower_id",
                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                  foreign_key: "followed_id",
                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:omniauthable,
          authentication_keys: [:username]
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  # 登録時に email を不要にする
  def email_required?
    false
  end
  def email_changed?
    false
  end
  def will_save_change_to_email?
    false
  end
  
  
  def follow(other_user)
    following << other_user
  end
  
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  def following?(other_user)
    following.include?(other_user)
  end
  
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end
  
    private

      def user_params
        params.require(:user).permit(:username,:password,
                                  :password_confirmation)
  　　　 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(
      user_id: current_user.id,
      post_id: params[:micropost_id]
      )
    @like.save
      redirect_to(root_path)
  end
  
  def destroy
    @likes = Like.find_by(
      user_id: @current_user.id,
      post_id: params[:micropost_id]
      )
     redirect_to("/users/index")
  end
  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only:[:post]
  before_action :correct_user,   only:[:destroy]
  
  def post
    @micropost = current_user.microposts.build
  end
  
  def show
    @micropost = Micropost.find_by(id: params[:id])
    @user = @micropost.user
  end
  
  def edit
  end
  
  def update
  end
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  private
  
   def micropost_params
    params.require(:micropost).permit(:content, :picture)
   end
      
   def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
   end
    
   def logged_in_user
    unless logged_in?
     store_location
     flash[:danger] = "Please log in."
     redirect_to login_url
    end
   end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end
  
  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @searches = Search.search(params[:search])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if logged_in?
      @feed_items = current_user.feed.all
    end
  end
  
  def contact
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    callback_from :facebook
  end
 
  private
 
  def callback_from(provider)
    provider = provider.to_s
 
    @user = User.find_for_oauth(request.env['omniauth.auth'])
 
    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  
  def facebook
    callback_for(:facebook)
  end
  
  def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
  
  def index
     @users = User.all
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @micropost = Micropost.find_by(id: params[:id])
    @microposts = @user.microposts
  end
  
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.all
    render 'show_follow'
  end
  
  def followers
    @title = "Followed"
    @user = User.find(params[:id])
    @users = @user.followers.all
    render 'show_follow'
  end
  
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  
  def user_params
    params.require(:user).permit(:username, :fullname, :website,
                                  :profile, :mailadress, :callnumber, :sex)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def current_user?(user)
    user == current_user
  end
  
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.mailadress.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
  
end

app/views/layouts/_footer.html.erb
<div class="center">
<footer class="footer">
  <ul>
     <%= link_to "投稿", '/post',class: "btn btn-lg btn-primary" %>
  </ul>
</footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Sample_instagram", root_path, id: "logo" %>
    <ul class="nav navbar-nav navbar-right">
      <li class="search"><%= render 'searches/index' %></li>
      <li><%= link_to "Top", root_path %> </li>
      <% if logged_in? %>
      <li><%= link_to "Notification", '#' %></li>
      <li><%= link_to "Mypage", user_path(current_user) %></li>
      <li><%= link_to "Log_out", destroy_user_session_path, method: :delete%></li>
      <% end %>
    </ul>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | SampleInstagram</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
 
  <span class="user">
    <%= link_to micropost.user.username, micropost.user %>
  </span>
  
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  
    <%= link_to "詳細",micropost_path(micropost.id) %>
  <% if current_user?(micropost.user) %>
      <%= link_to "削除", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/microposts/post.html.erb
<% provide(:title, "Post") %>

<%= render 'shared/micropost_form' %>

app/views/microposts/show.html.erb
<% provide(:title, "post detail") %>

<span><%= @micropost.content %> 
 <%= image_tag @micropost.picture.url if @micropost.picture? %>
</span>
<% if Like.find_by(user_id: @user.id, post_id: @micropost.id) %>
  <%= link_to("いいね！済み", "/likes/#{@micropost.id}/destroy", {method: "post"})%>
<% else %>
  <%= link_to("いいね！", "/likes/#{@micropost.id}/create", {method: "post"}) %>
<% end %>

app/views/searches/_index.html.erb
<%= form_tag searches_path, :method => 'get' do %> 
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

app/views/searches/index.html.erb
<p>検索結果</p>

app/views/shared/_feed.html.erb
<%= render @feed_items %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %> 
<div class=post>
  <%= f.text_area :content %><br />
</div>
  <%= f.submit "アップロード" %>
  <span class="picture">
    <%= f.file_field :picture %>
  </span>
<% end %>
<p class="red">必ず画像を選択してください</p>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div>
  
  
  <a href= "<%= following_user_path(@user) %>">
    <strong>
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href= "<%= followers_user_path(@user) %>">
    <strong>
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title,"contact") %>
<h1 class="contact">楽しむこと</h1>

app/views/static_pages/home.html.erb
<div class="center ">
<% provide(:title, "Top") %>
<% if logged_in? %>
  <ol class="microposts">
    <%= render 'shared/feed' %>
  </ol>
<% else %>
<h2>Welcome to Sample_instagram</h2>
<%= link_to "Please Sign up!", new_user_session_path, class: "btn btn-lg btn-primary" %>
<% end %>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー中", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>プロフィール編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <h4>公開情報</h4>
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :fullname %>
      <%= f.text_field :fullname, class: 'form-control' %>
      
      <%= f.label :website %>
      <%= f.text_field :website, class: 'form-control' %>
      
      <%= f.label :profile %>
      <%= f.text_field :profile, class: 'form-control' %>
      
      <h4>非公開情報</h4>
      <%= f.label :mailadress %>
      <%= f.text_field :mailadress, class: 'form-control' %>

      <%= f.label :callnumber%>
      <%= f.text_field :callnumber, class: 'form-control' %>
      
      <%= f.label :sex %>
      <%= f.text_field :sex, class: 'form-control' %>
      
      <%= f.submit "更新", class: "btn btn-primary" %>
    <% end %>
    <%= link_to "パスワード変更", edit_user_registration_path %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<h1>All users</h1>
 
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= user.username %>
    </li>
  <% end %>
</ul>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<h4>ユーザーネーム： <%= current_user.username %> </h4>

app/views/users/show.html.erb
<% provide(:title , "Mypage") %>
<div class = "show">
  <% if not @user.mailadress == nil %>
  <h1>
    <%= gravatar_for @user %>
  </h1>
  <% end %>
  <h4 >
     <%= @user.username %> 
  </h4>
  <div >
    <% if current_user?(@user) %>
      <%= link_to '編集', edit_user_path(current_user) %>
    <% else %>
      <%= render 'follow_form' if logged_in?  %>
    <% end %>
    
  </div>
  <div>
    投稿数 <%= @user.microposts.count %>
    <%= render 'shared/stats' %>

    <h4>自己紹介</h4>
      <p><%= @user.profile %></p>
    <div >
      投稿
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<%= @title %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= user.username %>
    </li>
  <% end %>
</ul>